# Generated by Django 3.1.4 on 2020-12-29 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20201229_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2020, 12, 29, 6, 43, 4, 202740, tzinfo=utc)),
        ),
    ]
