# Generated by Django 3.1.4 on 2020-12-29 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20201229_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loan_amount', models.IntegerField()),
                ('tenure_period', models.CharField(max_length=100)),
                ('rate_of_interest', models.CharField(max_length=50)),
                ('interest_amount', models.FloatField()),
                ('amount_to_be_paid', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2020, 12, 29, 9, 54, 8, 93909, tzinfo=utc)),
        ),
    ]
