# Generated by Django 3.1.4 on 2020-12-29 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auto_20201229_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2020, 12, 29, 12, 4, 59, 896225, tzinfo=utc)),
        ),
    ]
